layout_spectrum: 0.11248410143889487
typography_spectrum: 0.8895803350023925
color:
  brandStrength: 0.016688083996996284
  lightness: 0.9464968715328723
  saturation: 0.1728848684579134
  rhythmicContrast: 0.32429560529999435
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Rapidtech
navigation:
  - name: RAIDTECH
    url: 'http://rapidtech.computer'
    type: external
  - name: RAPIDTECH
    url: 'http://www.rapidtech.guru'
    type: external
